version: "3"
services:
  teamcity-agent:
    privileged: true
    user: 0
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      dockerfile: ./Dockerfile
    ports:
      - 9090:9090
    deploy:
        resources:
            limits:
                memory: 3G
    #volumes:
      #- ${CONF_PATH:-~/Workspace/TeamCity/agent/}:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=${SERVER_URL}
      - AGENT_NAME=${AGENT_NAME}
      - DOCKER_IN_DOCKER=${DIND}
endpoints:
- path: /
  service: teamcity-agent
  port: 9090
