version: "3"
services:
  teamcity-agent:
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    image: teamcity-android-agent
    deploy:
        resources:
            limits:
                memory: 6G
    #volumes:
      #- ${CONF_PATH:-~/Workspace/TeamCity/agent/}:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=${SERVER_URL}
