version: "3"
services:
  teamcity-agent:
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    build:
      context: teamcity-agent
      dockerfile: ./Dockerfile
    deploy:
        resources:
            limits:
                memory: 3G
    #volumes:
      #- ${CONF_PATH:-~/Workspace/TeamCity/agent/}:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=${SERVER_URL}
